version: 1.0.0
compose-app: docker-compose
service-groups:
  - name: airflow
    project-name: alertflow
    compose-path: containers/compose.yaml
    env-file: .env
    services:
      default: postgres,redis,airflow
      list:
        - name: postgres
        - name: redis
        - name: airflow
