version: 1.0.0
compose-app: docker-compose
service-groups:
  - name: base
    project-name: alertflow
    compose-path: docker/compose-base.yaml
    env-file: .env
    services:
      default: base
      list:
        - name: base

  - name: airflow
    project-name: alertflow
    compose-path: docker/compose.yaml
    env-file: .env
    services:
      default: core_postgres,core_redis,webserver,core_scheduler,core_worker,core_triggerer
      list:
        - name: core_postgres
        - name: core_redis
        - name: webserver
        - name: core_scheduler
        - name: core_worker
        - name: core_triggerer
        - name: core_flower
