repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer

  - repo: local
    hooks:
    - entry: blue
      id: blue
      name: blue
      exclude: |
        (?x)(
          docs
        )
      files: ""
      language: system
      pass_filenames: true
      stages:
        - commit
      types:
        - python
        - file
        - python

    - entry: flake8
      exclude: ^$
      files: ""
      id: flake8
      language: python
      name: flake8
      pass_filenames: true
      stages:
        - commit
      types:
        - python

    - entry: isort
      exclude: "^.*/js/.*$"
      files: ""
      id: isort
      language: python
      name: isort
      pass_filenames: true
      stages:
        - commit
      types:
        - python

    - id: shellcheck
      name: shellcheck
      language: system
      entry: shellcheck
      types_or:
        - sh
        - shell
        - ash
        - bash
        - bats
        - dash
        - ksh
