ENV=${ENV:-dev}

# Core
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
AIRFLOW_HOME=${AIRFLOW_HOME:-/opt/airflow}
AIRFLOW_PORT=${AIRFLOW_PORT:-8080}

# Web
_AIRFLOW_WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME}
_AIRFLOW_WWW_USER_PASSWORD=${_AIRFLOW_WWW_USER_USERNAME}
_AIRFLOW_WWW_USER_EMAIL=${_AIRFLOW_WWW_USER_EMAIL}
_AIRFLOW_WWW_USER_FIRST_NAME=${_AIRFLOW_WWW_USER_FIRST_NAME}
_AIRFLOW_WWW_USER_LAST_NAME=${_AIRFLOW_WWW_USER_LAST_NAME}

# Email
AIRFLOW__SMTP__SMTP_HOST=${AIRFLOW__SMTP__SMTP_HOST}
AIRFLOW__SMTP__SMTP_STARTTLS=${AIRFLOW__SMTP__SMTP_STARTTLS}
AIRFLOW__SMTP__SMTP_PORT=${AIRFLOW__SMTP__SMTP_PORT}
AIRFLOW__SMTP__SMTP_MAIL_FROM=${AIRFLOW__SMTP__SMTP_MAIL_FROM}

# External Postgres Connection
# https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html
PSQL_USER_MAIN=${PSQL_USER_MAIN}
PSQL_PASSWORD_MAIN=${PSQL_PASSWORD_MAIN}
PSQL_HOST_MAIN=${PSQL_HOST_MAIN}
PSQL_PORT_MAIN=${PSQL_PORT_MAIN}
PSQL_DB_MAIN=${PSQL_DB_MAIN}
PSQL_URI_MAIN=postgresql://${PSQL_USER_MAIN}:${PSQL_PASSWORD_MAIN}@${PSQL_HOST_MAIN}:${PSQL_PORT_MAIN}/${PSQL_DB_MAIN}

# Satellite Weather (format: CDSAPI_KEY="UID:KEY")
# https://cds.climate.copernicus.eu/user/{MY_USER}
CDSAPI_KEY=${CDSAPI_KEY}

# Extras
AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
AIRFLOW__CORE__INTERNAL_API_SECRET_KEY=${AIRFLOW__CORE__INTERNAL_API_SECRET_KEY}
AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:-true}
AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=${AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK:-false}
AIRFLOW__API_AUTH__JWT_SECRET=${AIRFLOW__API_AUTH__JWT_SECRET}
AIRFLOW__API_AUTH__JWT_ISSUER=${AIRFLOW__API_AUTH__JWT_ISSUER:-airflow}
AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
AIRFLOW__LOGGING__LOGGING_LEVEL=${AIRFLOW__LOGGING__LOGGING_LEVEL:-INFO}
AIRFLOW__SENTRY__SENTRY_ON=${AIRFLOW__SENTRY__SENTRY_ON:-true}
AIRFLOW__SENTRY__SENTRY_DSN=${AIRFLOW__SENTRY__SENTRY_DSN}
