services:
  airflow-worker:
    networks:
        - infodengue-dev_infodengue

  airflow-scheduler:
    networks:
        - infodengue-dev_infodengue

  airflow-apiserver:
    networks:
        - infodengue-dev_infodengue

networks:
  infodengue-dev_infodengue:
    external: true
