services:
  base:
    env_file: ../.env
    environment:
      AIRFLOW_HOME: /opt/alertflow
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    entrypoint: /bin/bash
