services:
  airflow-worker:
    networks:
        - infodengue-prod_infodengue

  airflow-scheduler:
    networks:
        - infodengue-prod_infodengue

  airflow-apiserver:
    networks:
        - infodengue-prod_infodengue

networks:
  infodengue-prod_infodengue:
    external: true
