name: AlertFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENV: dev
  AIRFLOW_PROJ_DIR: /home/runner/work/AlertFlow/AlertFlow/alertflow
  AIRFLOW_HOME: /opt/airflow
  AIRFLOW_PORT: 8081
  AIRFLOW_UID: 1000
  HOST_UID: 1000
  HOST_GID: 1000
  _AIRFLOW_WWW_USER_USERNAME: ci
  _AIRFLOW_WWW_USER_PASSWORD: ci
  AIRFLOW_PSQL_USER_MAIN: ${{ secrets.CI_PSQL_USER }}
  AIRFLOW_PSQL_PASSWORD_MAIN: ${{ secrets.CI_PSQL_PASSWORD }}
  AIRFLOW_PSQL_HOST_MAIN: ${{ secrets.CI_PSQL_HOST }}
  AIRFLOW_PSQL_PORT_MAIN: ${{ secrets.CI_PSQL_PORT }}
  AIRFLOW_PSQL_DB_MAIN: ${{ secrets.CI_PSQL_DB }}
  EPISCANNER_HOST_DATA: /home/runner/work/AlertFlow/AlertFlow/alertflow/episcanner-downloader/epi_scanner/data/

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 55
    defaults:
      run:
        shell: bash -l {0}
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    # Check if the repository is a fork
    - name: Check if repository is a fork
      run: |
        if [[ "${{ github.event.repository.fork }}" == "true" ]]; then
          export AIRFLOW_PSQL_USER_MAIN="${{ secrets.CI_PSQL_USER_FORK }}"
          export AIRFLOW_PSQL_PASSWORD_MAIN="${{ secrets.CI_PSQL_PASSWORD_FORK }}"
          export AIRFLOW_PSQL_HOST_MAIN="${{ secrets.CI_PSQL_HOST_FORK }}"
          export AIRFLOW_PSQL_PORT_MAIN="${{ secrets.CI_PSQL_PORT_FORK }}"
          export AIRFLOW_PSQL_DB_MAIN="${{ secrets.CI_PSQL_DB_FORK }}"
        else
          export AIRFLOW_PSQL_USER_MAIN="${{ secrets.CI_PSQL_USER }}"
          export AIRFLOW_PSQL_PASSWORD_MAIN="${{ secrets.CI_PSQL_PASSWORD }}"
          export AIRFLOW_PSQL_HOST_MAIN="${{ secrets.CI_PSQL_HOST }}"
          export AIRFLOW_PSQL_PORT_MAIN="${{ secrets.CI_PSQL_PORT }}"
          export AIRFLOW_PSQL_DB_MAIN="${{ secrets.CI_PSQL_DB }}"
        fi

    - name: Semantic Release Title Check
      uses: osl-incubator/semantic-release-pr-title-check@v1.4.1
      with:
        convention-name: conventionalcommits

    - name: Install Conda Dependencies
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/env.yaml
        channels: conda-forge,nodefaults
        activate-environment: alertflow
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Create environment variables file
      run: |
        envsubst < env.tpl > .env

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint All Files
      run: |
        make linter

    - name: Create Docker network
      run: |
        docker network create infodengue-dev_infodengue

    - name: Build Base Image
      run: |
        sugar build

    - name: Start Airflow
      run: |
        sugar up --options -d

    - name: Wait Containers
      run: |
        make containers-wait-all

    # - name: Setup tmate session
    #   if: "${{ failure() }}"
    #   uses: mxschmitt/action-tmate@v3
