name: AlertFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AIRFLOW_PROJ_HOST_DIR: /home/runner/work/AlertFlow/AlertFlow/alertflow
  AIRFLOW_IMAGE_NAME: apache/airflow:2.5.1
  HOST_UID: 1001

  _AIRFLOW_WWW_USER_USERNAME: ci
  _AIRFLOW_WWW_USER_PASSWORD: ci

  PSQL_USER: ${{ secrets.CI_PSQL_USER }}
  PSQL_PASSWORD: ${{ secrets.CI_PSQL_PASSWORD }}
  PSQL_HOST: ${{ secrets.CI_PSQL_HOST }}
  PSQL_PORT: ${{ secrets.CI_PSQL_PORT }}
  PSQL_DB: ${{ secrets.CI_PSQL_DB }}

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 55
    defaults:
      run:
        shell: bash -l {0}
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    - name: Semantic Release Title Check
      uses: osl-incubator/semantic-release-pr-title-check@v1.4.1
      with:
        convention-name: conventionalcommits

    - name: Install Conda Dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/env.yaml
        channels: conda-forge,nodefaults
        activate-environment: alertflow
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install Poetry Dependencies
      run: |
        touch .env
        poetry install

    - name: Lint All Files
      run: |
        make linter

    - name: Build Base Image
      run: |
        make containers-build

    - name: Start Airflow
      run: |
        make containers-start

    # TODO
    # - name: Wait Containers
    #   run: |
    #     make containers-wait
